#!/usr/bin/env python3
"""Generate harness adapter instruction files from starter-kit templates."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]

GENERATED_MARKER = "Generated by tools/scaffold/gen-harness-instructions.py."
HEADER = f"""<!--
{GENERATED_MARKER}
Canonical source: AGENTS.md.
Do not hand-edit long-lived rules here; update AGENTS.md and regenerate.
-->

"""

HARNESS_OUTPUTS = {
    "claude": ("templates/harness-adapters/CLAUDE.md", "CLAUDE.md"),
    "codex": ("templates/harness-adapters/codex-agents.md", "docs/generated/codex-agents.md"),
    "openai": ("templates/harness-adapters/openai-agents-sdk.md", "docs/generated/openai-agents-sdk.md"),
    "mcp": ("templates/harness-adapters/mcp-config.md", "docs/generated/mcp-config.md"),
}


def is_generated(path: Path) -> bool:
    if not path.exists():
        return False
    return GENERATED_MARKER in path.read_text(encoding="utf-8", errors="replace")


def canonical_excerpt(project: Path) -> str:
    source = project / "AGENTS.md"
    if not source.is_file():
        raise SystemExit(f"missing canonical source: {source}")
    text = source.read_text(encoding="utf-8")
    return "\n## Canonical AGENTS.md\n\n" + text.rstrip() + "\n"


def generate(project: Path, harness: str, *, force: bool) -> Path:
    template_rel, output_rel = HARNESS_OUTPUTS[harness]
    template = ROOT / template_rel
    target = project / output_rel
    if target.exists() and not force and not is_generated(target):
        raise SystemExit(f"refusing to overwrite non-generated file: {target}")

    adapter = template.read_text(encoding="utf-8").rstrip()
    body = HEADER + adapter + canonical_excerpt(project)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8")
    return target


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", default=".", help="Project root containing AGENTS.md")
    parser.add_argument("--harness", choices=sorted(HARNESS_OUTPUTS))
    parser.add_argument("--list-harnesses", action="store_true")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    if args.list_harnesses:
        for name in sorted(HARNESS_OUTPUTS):
            print(name)
        return 0
    if not args.harness:
        parser.error("--harness is required unless --list-harnesses is used")

    target = generate(Path(args.project).resolve(), args.harness, force=args.force)
    print(f"generated {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

